# Generated by Django 4.2 on 2026-06-21 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=50)),
                ('map_file_path', models.CharField(max_length=200)),
                ('annotation_file_path', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_index', models.IntegerField(help_text='任务索引，来自ROS消息', unique=True)),
                ('status', models.IntegerField(choices=[(0, '运行中'), (1, '成功'), (2, '失败')], default=0)),
                ('message', models.CharField(blank=True, default='', max_length=100)),
                ('result_detail', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('waypoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('waypoint_name', models.CharField(max_length=50)),
                ('waypoint_type', models.IntegerField(choices=[(0, '取货点'), (1, '放货点')], default=0)),
                ('cargo_type', models.IntegerField(blank=True, choices=[(0, '货物A'), (1, '货物B'), (2, '货物C')], null=True, verbose_name='货物类型')),
                ('px', models.FloatField()),
                ('py', models.FloatField()),
                ('pz', models.FloatField()),
                ('orientation', models.FloatField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='app0.map')),
            ],
        ),
    ]
